name: mine_com_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1


environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  dartssh2: ^2.13.0
  xterm: ^4.0.0
  postgres: ^3.5.8
  web_socket_channel: ^3.0.3
  http: ^1.2.0


flutter:
  uses-material-design: true
